version : "3"

services:
  app:
    build:
      context: .
    ports:
      - "8084"
    volumes:
      - ./app:/app
    #command: >
    #  
    #  sh -c "python manage.py wait_for_db &&
    #         python manage.py migrate &&
    #         python manage.py runserver 0.0.0.0:8000"
    command: sh -c "python manage.py wait_for_db && uwsgi --socket :8084 --http :8000 --buffer-size=32768  --module  app.wsgi "

    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - VIRTUAL_HOST=foodrunner.lvh.me
      - VIRTUAL_PROTO= uwsgi
      - LETSENCRYPT_HOST=foodrunner.lvh.me
      - LETSENCRYPT_EMAIL=mm@vimmoda.com
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    
networks:
  default:
    external:
      name: nginx-proxy
